// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmikwzkmtlfohshjyqcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtaWt3emttdGxmb2hzaGp5cWN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjQyODksImV4cCI6MjA2MTUwMDI4OX0.4BAoWiQ3xKGnytWrHHhstdotPLPpGbX0rcBbsXETqIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);